#!/usr/bin/python3
import sys

def catalog_files (fname):
  """add <fname> to the calatog

  Args:
      fname (_string_): _file or directory path_
  """
  print (fname)
  
catalog_files (sys.argv [2])
